parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    command_handlers:
        namespace: App\Diet\Application\Command\
        resource: '../src/Diet/Application/Command/*Handler*'
        tags: [command_handler]
        public: true

    query_executors:
        namespace: App\Diet\Application\Query\
        resource: '../src/Diet/Application/Query/*Executor*'
        tags: [query_executor]
        public: true

    App\Diet\Presentation\Console\PrepareDietPdfConsole:
        arguments:
            - '@App\Diet\Application\QueryBus'
            - '@App\Diet\Application\Service\DietPdfGenerator'

    App\Diet\Presentation\Console\PrepareShoppingListPdfConsole:
        arguments:
            - '@App\Diet\Application\QueryBus'
            - '@App\Diet\Application\Service\ShoppingListPdfGenerator'

    App\Diet\Presentation\Console\PrepareRecipesListPdfConsole:
        arguments:
            - '@App\Diet\Application\QueryBus'
            - '@App\Diet\Application\Service\RecipesListPdfGenerator'